### ISSUE TITLE
[Task] 방문한 페이지 기능 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#103]
### ISSUE
  - Group: `client`
  - Type: feature`
  - Detail: 상세정보 페이지를 방문한 식당에 대해 리스트를 제공하는 기능 구현
### TODO
- [ ] <ShopDetail/> <ShopDetail2/> 접속시 해당 식당에 대한 정보를 로컬스토리지에 저장 
- [ ] 로컬스토리지에 저장한 데이터를 리스트로 출력하는 로직 구현
- [ ] 이미 방문한 페이지에 대해 중복해서 저장하지 않는 로직 구현
### Estimated time

`3h`
