### ISSUE TITLE
[Task] 상세정보 페이지 로직 리팩토링

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#104]
### ISSUE
  - Group: `client`
  - Type: `bug`
  - Detail: 상세정보 페이지가 2가지 종류 컴포넌트로 나누어 작성되어있던 것을 하나로 통합하는 로직으로 리팩토링
### TODO
- [ ] intro 페이지 axios 요청을 통해 shop 테이블과 shop_pic 테이블 정보 받아오는 로직으로 수정 
- [ ] ShopDetai과 ShopDetail 에 각각 map_id, shop_id 를 전달하던 방식에서 shop_id로 통일하여 하나의 컴포넌트로
      상세정보 페이지를 다룰 수 있도록 수정
- [ ] match.params.id 속성을 통해 shop_id 값을 전달, 리뷰작성 페이지에서도 해당 속성 사용할수 있도록 파라미터 전달
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
