### ISSUE TITLE
[Task] 즐겨찾기 db 생성, api 컨트롤러 문서 작성

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#105]
### ISSUE
  - Group: `client`, `server`
  - Type: `feature`
  - Detail: 즐겨찾기 기능을 위한 테이블 생성, 해당 테이블 정보를 기반으로한 api 컨트롤러 문서 작성
### TODO
- [ ] 즐겨찾기목록을 위한 테이블 생성
- [ ] 로그인 했을때 즐겨찾기 목록을 기반으로 shop정보를 가져와 쿠키에 전달하는 로직 구현
- [ ] 쿠키가 전달될 수 있도록 axios 요청 옵션에 withCredentials : true 속성 추가
- [ ] 즐겨찾기를 추가/삭제하는 axios 요청 시 토큰을 기반으로 인증 후 해당 유저에 대한 신원을 확인하는 로직 구현
- [ ] 신원이 확인되었을때 bookmark 속성에 따라 추가/제거 분기 후 bookmark 테이블에 정보 추가/제거
- [ ] bookmark 테이블 정보를 바탕으로 shop 테이블에서 정보 조회, 해당 정보 배열에 담은 후 JSON.stringify() 형식으로 쿠키에 담기
- [ ] 추가/제거에 따른 메시지 담은 후 응답
- [ ] 로그아웃 시 쿠키 소멸하도록 res.clearCookie() 작성
### Estimated time

`3h`

Labels(라벨 종류)
Group : client, server
