### ISSUE TITLE
[Task] 즐겨찾기 api 요청 핸들러 작성

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#106]
### ISSUE
  - Group: `client`
  - Type: `feature``
  - Detail: 즐겨찾기 api 요청에 대한 핸들러 작성
### TODO
- [ ] 상세정보 페이지의 즐겨찾기(별표모양)를 기준으로 기능 구현 
- [ ] 별표 모양 클릭시 해당 핸들러 발생하도록 함수 정의
- [ ] 핸들러 함수 호출시 상태에 따라 추가/제거 axios 요청 보내도록 분기 후 로직 작성
- [ ] 인증 실패시 로그인 모달창이 뜨도록 구현
- [ ] 추가/제거 완료 시 다른 응답이 오는지 확인
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
