### ISSUE TITLE
[Task] 즐겨찾기 상태에 따른 별모양 상태 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#107]
### ISSUE
  - Group: `client`, `server`, `sr`
  - Type: `bug`, `feature`, `delete`
  - Detail: fix actions from client redux
### TODO
- [ ] 별모양 상태를 구분하는 상태변수 정의
- [ ] axios 추가/제거 응답에 따라 상태변수가 변화하도록 상태변화함수 호출 
- [ ] 상태 변화에 따라 해당 태크 className 변경, 'on' className이 붙은경우 color: yellow; 속성 추가되도록 구현
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
