### ISSUE TITLE
[Task] 즐겨찾기 로직 여러 컴포넌트에 적용

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#108]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 즐겨찾기 기능 여러 컴포넌트에 적용하기
### TODO
- [ ] 즐겨찾기 리스트에 쿠키정보(즐겨찾기 정보)에 따라 리스트 변화하도록 구현
- [ ] 페이지 렌더링시 쿠키 정보를 조회하여 즐겨찾기가 추가된 리스트에 대해 별표아이콘 className 변경
- [ ] className 변경시 color: yellow; 적용
- [ ] 즐겨찾기 추가/제거 기능 즐겨찾기 리스트에서도 가능하도록 구현
- [ ] EditorPick 페이지 (위치별 식당 리스트) 같은 방식으로 즐겨찾기 기능 구현
### Estimated time

`3h`

Labels(라벨 종류)
Group : client, server
