### ISSUE TITLE
[Task] 방문한 페이지와 즐겨찾기 분기 나누어 표현 작업

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#109]
### ISSUE
  - Group: `client`
  - Type: `feature``
  - Detail: 방문한 페이지, 즐겨찾기를 분기를 나누어 보여주는 로직 작성
### TODO
- [ ] 분기를 나누어주는 상태변수 정의
- [ ] 상태변수의 상태에 따라 둘 중 하나를 렌더링하는 로직 작성
- [ ] '최근 본 맛집', '가고싶다' 를 클릭시 해당 리스트를 보여주도록 상태변화 함수 호출
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
