### ISSUE TITLE
[Task] 로그아웃 상태에서 즐겨찾기 기능 접근 못하도록 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#110]
### ISSUE
  - Group: `client`
  - Type: `bug`
  - Detail: 로그아웃 상태에서 즐겨찾기 기능 접근 못하도록 
### TODO
- [ ] 로그아웃 시 별표아이콘 클릭했을때 로그인 모달 창 뜨도록 구현
- [ ] 즐겨찾기 리스트 '가고 싶다' 클릭시 로그인 모달 창 뜨도록 구현
- [ ] 로그아웃 상태에서 이전 로그인한 상태에서의 즐겨찾기 상태를 표현하지 않도록 새로고침 구현
- [ ] 로그인 모달창과 즐겨찾기 모달창의 우선순위 설정(z-index)
### Estimated time
`3h`

Labels(라벨 종류)
Group : client
