### ISSUE TITLE
[Task] 위치기반 식당 리스트 페이지 기본 폼 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#112]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 위치기반 식당 리스트 페이지 기본 폼 구현
### TODO
- [ ] 식당 하나에 대한 컴포넌트 기본 폼구현
- [ ] 컴포넌트에 들어갈 데이터 더미데이터로 출력 테스트
- [ ] map 함수를 이용해 컴포넌트 반복하는 작업
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
