### ISSUE TITLE
[Task] 최다리뷰 8개 리스트 기본 폼 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#115]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 최다리뷰 8개 리스트 기본 컴포넌트 구현
### TODO
- [ ] 식당 이미지 8개를 띄워주는 기본 폼 구현
- [ ] 기본 폼에 더미이미지 출력을 통해 이미지 렌더링 테스트
- [ ] 메인페이지에 해당 컴포넌트 삽입
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
