### ISSUE TITLE
[Task] 최다리뷰 8개 리스트 데이터 출력

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#116]
### ISSUE
  - Group: `client`, `server`,
  - Type: `feature`
  - Detail: 최다리뷰 8개 리스트 데이터 출력
  - 
### TODO
- [ ] 리뷰가 가장 많은 shop 정보 8개를 내림차순으로 가져오는 api 작성
- [ ] 페이지 렌더링시 api 호출되도록 useEffect 작성
- [ ] api 요청을 통해 가져온 데이터를 통해 해당 식당 이미지 출력
### Estimated time

`3h`

Labels(라벨 종류)
Group : client, server
