### ISSUE TITLE
[Task] 최다리뷰 8개 리스트 상세페이지와 연결 작업

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#117]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 최다리뷰 8개 리스트 상세페이지와 연결 작업
### TODO
- [ ] 해당 식당 이미지에 라우터 링크 연결
- [ ] 라우터 파라미터에 shop_id 전달
- [ ] match.params.id 에 해당 파라미터 전달되는지 확인
- [ ] 정상적으로 상세페이지 렌더링되는지 확인
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
