### ISSUE TITLE
[Task] 메인페이지 슬라이드 CSS 마무리

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#158]
### ISSUE
  - Group: `client`
  - Type: `styling`,
  - Detail:  메인페이지 슬라이드 CSS 마무리
### TODO
- [ ] Swiper 슬라이드를 이용하여 슬라이드 구현
- [ ] 슬라이더 간 간격 및 이미지 크기 조정
- [ ] 각 슬라이드 너비 및 높이 조정
- [ ] 슬라이드 제목(음식점 이름) 및 종류 스타일 수정
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
