### ISSUE TITLE
[Task] 지역별 추천 페이지 CSS 마무리

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#159]
### ISSUE
  - Group: `client`
  - Type: `스타일링`
  - Detail:  지역별 추천 페이지 CSS 마무리
### TODO
- [ ] 전체 폼 너비 및 간격 조정
- [ ] 이미지 배치 및 폰트 정렬
- [ ] 헤더 아래 타이틀 추가
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
