### ISSUE TITLE
[Task] 인트로 페이지 작성

### ISSUE THREAD

**Issue by EuilimChoi** [codestates/Momukzzi#16]
### ISSUE
  - Group: `client`
  - Type: ``feature`
  - Detail: 인트로 페이지 작성
  - 
### TODO
- [ ] 카카오맵 api 기반 위치 추적 기능
- [ ] 카카오맵 api 기반 근처 식당 리스트 추출
- [ ] 해당 리스트 기반으로 음식점 메뉴, 이미지 등 크롤링

### Estimated time
`3h`
