### ISSUE TITLE
[Task] 즐겨찾기 CSS 작업 및 별표 아이콘 수정

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#160]
### ISSUE
  - Group: `client`
  - Type:  `styling`
  - Detail: 즐겨찾기 CSS 작업 및 별표 아이콘 수정
### TODO
- [ ] 즐겨찾기 기본폼 CSS 마무리
- [ ] 별표 아이콘 수정
- [ ] 카테고리 클릭 시 스타일링 추가
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
