### ISSUE TITLE
[Task] 인트로 페이지 CSS 작업 및 추천 기능 추가

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#161]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 인트로 페이지 CSS 작업 및 추천 기능 추가
### TODO
- [ ] 인트로 페이지 기본 CSS 마무리
- [ ] 추천버튼에 기능 추가
- [ ] 스크롤 이동 버튼 픽셀 조정
### Estimated time

`3h`

Labels(라벨 종류)
Group : client
