### ISSUE TITLE
[Task] 모달 기능 및 로그인 기본 폼 구현

### ISSUE THREAD

**Issue by hyukzz** [codestates/Momukzzi#19]
### ISSUE
  - Group: `client`
  - Type:  `feature`
  - Detail: 모달 기능 및 로그인 기본 폼 구현 
### TODO
- [x] 헤더부분 로그인 버튼에 모달 기능 구현
- [x] HTML, CSS를 사용해 로그인 기본 폼 구현
- [x] modal outside click 시 modal 창 꺼지는 기능 구현
- [x] 컴포넌트로 관리하며 리액트 환경에서 정상 작동하는지 테스트

### Estimated time

`3h`
