### ISSUE TITLE
[Task] 메인페이지 푸터 기본 폼 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#39]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 메인 페이지 푸터 기본 폼 구현
### TODO
- [x] 로고, 깃헙아이콘, 팀원 이름 배치
- [x] 각 아이콘과 팀원 이름에 링크 연결
- [x] 브라우저 하단에 공백없이 배치
### Estimated time
`3h`
