### ISSUE TITLE
[Task] 메인페이지 음식점 슬라이드 목록 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#40]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 메인페이지 음식점 목록 슬라이드 형태로 구현
### TODO
- [x] Swiper 라이브러리를 이용한 슬라이드 구현
- [x] 음식점 별로 슬라이드에 이미지를 배치하여 화면에 리스트 출력
- [x] 더미데이터와 map 함수를 이용한 컴포넌트 반복
### Estimated time
`3h`
