### ISSUE TITLE
[Task] 리뷰 작성 페이지 기능 구현 마무리

### ISSUE THREAD

**Issue by yomae** [codestates/Momukzzi#58]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 리뷰 작성 페이지 구현 마무리
 
### TODO
- [x] 평점 버튼 만들기 및 기능 구현
- [x] 이미지 업로드 및 썸네일 미리보기 기능 구현
- [x] 폼 객체 서버에 post 요청

### Estimated time
`6h`
