### ISSUE TITLE
[SR] 이슈 기본 양식 설정

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#6]
### ISSUE
  - Group: `sr`
### TODO
- [x] Issue Tack Card 양식 설정
- [x] KPT 양식 설정
- [x] Dev_log 양식 설정
- [x] Error Handling 양식 설정
### Estimated time
`2h`
