### ISSUE TITLE
[Task] 회원가입 페이지 가입완료 기능 구현

### ISSUE THREAD

**Issue by rkdghwnd** [codestates/Momukzzi#9]
### ISSUE
  - Group: `client`
  - Type: `feature`
  - Detail: 해당하는 유효성 검증을 통과했을때 회원가입이 완료되는 기능을 구현
### TODO
- [x] 유효성 검증을 모두 통과할경우 AXIOS로 회원정보를 전송하는 로직 구현
- [x] 예외상황에 대한 에러 처리 
- [ ] 회원가입이 완료되었을 경우 메인페이지로 리다이렉트 되도록 구현
### Estimated time

`3h`
